ROOT_LOG_LEVEL: DEBUG
SQL_LOG_LEVEL: DEBUG
JDBC_BIND_LOG_LEVEL: TRACE

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: code
    password: code
    driver-class-name: org.h2.Driver
    hikari:                     # DB Connection Pool 설정. 현재 지정한 값들은 모두 기본 값에 해당.
      connection-timeout: 30000 # - 타임아웃 값
      validation-timeout: 5000  # - 유효한 타임아웃
      minimum-idle: 10          # - 유휴 커넥션 수
      max-lifetime: 1800000     # - 커넥션의 최대 수명
      maximum-pool-size: 10     # - 최대 풀 사이즈
      idle-timeout: 600000      # - 연결을 위한 최대 유휴 시간
      auto-commit: true         # - auto commit 여부

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true # h2 console 활성화 여부. 기본 값: false
      path: /h2     # h2 console 접속 경로. 기본 값 : /h2-console

  # i18n : 다국어 처리를 위한 메시지 국제화
  messages:
    basename: i18n/error # error.properties 지정
    encoding: UTF-8

  web:
    locale: ko_KR # 다국어 처리를 위한 로케일 지정. [ ko_KR , en_US ]

# LOG
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%clr(%-5p)][%thread][%clr(%logger{20}.%method){cyan}] - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%-5p][%thread][%logger{20}.%method] - %msg%n"

  file:
    name: ./logs/api-book.log

  level:
    io.dongvelop.bookmanagementsystem: ${ROOT_LOG_LEVEL}
    org.hibernate.SQL: ${SQL_LOG_LEVEL}
    org.hibernate.orm.jdbc.bind: ${JDBC_BIND_LOG_LEVEL}

  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i"
      total-size-cap: 1GB

springdoc:
  api-docs:
    enabled: true  # API 문서 활성화 (기본값: true)
  swagger-ui:
    enabled: true  # Swagger UI 활성화 (기본값: true)
    path: /swagger-ui.html  # Swagger UI 경로 변경 (기본값: /swagger-ui.html)
    operations-sorter: alpha  # API 정렬 기준 (alpha: 알파벳 순 정렬)
    tags-sorter: alpha  # 태그 정렬 기준
    doc-expansion: list  # API 문서 기본 확장 방식 (none, list, full)
    display-request-duration: true  # 요청 소요 시간 표시 여부
  cache:
    disabled: true  # 캐싱 비활성화 (API 변경 즉시 반영)
